### ISSUE TITLE
gta img tool

### ISSUE THREAD

**Issue by axb996** [geo-gta3/gxt#2]
close

**Comment by vakho10** [comment]
@1934291047o Sadly I have not read about the *.img format. Sounds like a good idea. I've found the explanation of format here: https://gtamods.com/wiki/IMG_archive
You can develop the tool yourself if it ain't too hard. I think the format is fairly simple.

**Comment by vakho10** [comment]
@1934291047o I may make a GTA3 IMG file editor myself. 
However, I am not planing on making San Andreas's version right now. I myself am a slow person too.
